__include__: [../deimv2/deimv2_hgnetv2_n_coco.yml]

output_dir: ./outputs/distill_deimv2_different/hgnetv2_n_from_dinov3_s_backbone

model: DEIMFGDDistiller

last_epoch: 120
epochs: 132

DEIMFGDDistiller:
  student_ckpt: ./best/deimv2_hgnetv2_n_coco.pth
  student:
    type: DEIM
    backbone:
      type: HGNetv2
      name: 'B0'
      return_idx: [2, 3]
      freeze_at: -1
      freeze_norm: false
      use_lab: true
    encoder:
      type: HybridEncoder
      in_channels: [512, 1024]
      feat_strides: [16, 32]
      hidden_dim: 128
      use_encoder_idx: [1]
      num_encoder_layers: 1
      nhead: 8
      dim_feedforward: 512
      dropout: 0.0
      enc_act: gelu
      expansion: 0.34
      depth_mult: 0.5
      act: silu
      version: dfine
    decoder:
      type: DEIMTransformer
      feat_channels: [128, 128]
      feat_strides: [16, 32]
      hidden_dim: 128
      num_levels: 2
      num_layers: 3
      eval_idx: -1
      num_queries: 300
      num_denoising: 100
      label_noise_ratio: 0.5
      box_noise_scale: 1.0
      reg_max: 32
      reg_scale: 4
      layer_scale: 1
      num_points: [6, 6]
      cross_attn_method: default
      query_select_method: default
  teacher:
    type: DEIM
    backbone:
      type: DINOv3STAs
      name: vit_tiny
      embed_dim: 192
      weights_path: ./ckpts/vitt_distill.pt
      interaction_indexes: [5, 8, 11]
      num_heads: 3
      finetune: true
    encoder:
      type: HybridEncoder
      in_channels: [192, 192, 192]
      feat_strides: [8, 16, 32]
      depth_mult: 0.67
      expansion: 0.34
      hidden_dim: 192
      dim_feedforward: 512
      num_encoder_layers: 1
      use_encoder_idx: [2]
      version: deim
      csp_type: csp2
      fuse_op: sum
    decoder:
      type: DEIMTransformer
      feat_channels: [192, 192, 192]
      feat_strides: [8, 16, 32]
      hidden_dim: 192
      dim_feedforward: 512
      num_layers: 4
      eval_idx: -1
      num_levels: 3
      num_points: [3, 6, 3]
  feature_pairs:
    - name: c4
      student_index: 0
      teacher_index: 1
      meta:
        source: encoder
        start_epoch: 124
    - name: c5
      student_index: 1
      teacher_index: 2
      meta:
        source: backbone
        start_epoch: 124
  teacher_ckpt: ./best/deimv2_dinov3_s_coco.pth

DEIMCriterion:
  distill_cfg:
    - name: c5
      weight: 0.35
      start_epoch: 124
      ramp_epochs: 6
      start_weight: 0.1
      loss:
        type: FGDFeatureLoss
        student_channels: 128
        teacher_channels: 192
        temp: 0.9
        alpha_fgd: 0.00034
        beta_fgd: 0.00005
        gamma_fgd: 0.00018
        lambda_fgd: 0.000001
    - name: c4
      weight: 0.22
      start_epoch: 126
      ramp_epochs: 6
      start_weight: 0.1
      loss:
        type: FGDFeatureLoss
        student_channels: 128
        teacher_channels: 192
        temp: 0.9
        alpha_fgd: 0.00034
        beta_fgd: 0.00005
        gamma_fgd: 0.00018
        lambda_fgd: 0.000001

train_dataloader:
  collate_fn:
    stop_epoch: 120
