__include__: [../deimv2/deimv2_dinov3_l_coco.yml]

output_dir: ./outputs/distill_deimv2/dinov3_l_from_x_encoder

model: DEIMFGDDistiller

DEIMFGDDistiller:
  student_ckpt: ./best/deimv2_dinov3_l_coco.pth
  student:
    type: DEIM
    backbone:
      type: DINOv3STAs
      name: dinov3_vits16
      embed_dim: 224
      weights_path: ./ckpts/dinov3_vits16_pretrain_lvd1689m-08c60483.pth
      interaction_indexes: [5, 8, 11]
      finetune: true
      conv_inplane: 32
      hidden_dim: 224
    encoder:
      type: HybridEncoder
      in_channels: [224, 224, 224]
      hidden_dim: 224
      dim_feedforward: 896
    decoder:
      type: DEIMTransformer
      feat_channels: [224, 224, 224]
      hidden_dim: 224
      dim_feedforward: 1792
      num_layers: 4
      eval_idx: -1
      num_points: [6, 6, 6]
  teacher:
    type: DEIM
    backbone:
      type: DINOv3STAs
      name: dinov3_vits16plus
      embed_dim: 256
      weights_path: ./ckpts/dinov3_vits16plus_pretrain_lvd1689m-4057cbaa.pth
      interaction_indexes: [5, 8, 11]
      finetune: true
      conv_inplane: 64
      hidden_dim: 256
    encoder:
      type: HybridEncoder
      in_channels: [256, 256, 256]
      hidden_dim: 256
      dim_feedforward: 1024
      expansion: 1.25
      depth_mult: 1.37
    decoder:
      type: DEIMTransformer
      feat_channels: [256, 256, 256]
      hidden_dim: 256
      dim_feedforward: 2048
      num_layers: 6
      eval_idx: -1
      num_points: [6, 6, 6]
  feature_pairs:
    - name: p3
      student_index: 0
      teacher_index: 0
      meta:
        source: encoder
        start_epoch: 60
    - name: p4
      student_index: 1
      teacher_index: 1
      meta:
        source: encoder
        start_epoch: 60
    - name: p5
      student_index: 2
      teacher_index: 2
      meta:
        source: encoder
        start_epoch: 60
  teacher_ckpt: ./outputs/deimv2_dinov3_x_coco/best_stg2.pth

DEIMCriterion:
  distill_cfg:
    - name: p5
      weight: 0.26
      start_epoch: 60
      ramp_epochs: 4
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 224
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00032
        beta_fgd: 0.00005
        gamma_fgd: 0.00018
        lambda_fgd: 0.000001
    - name: p4
      weight: 0.20
      start_epoch: 60
      ramp_epochs: 4
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 224
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00032
        beta_fgd: 0.00005
        gamma_fgd: 0.00018
        lambda_fgd: 0.000001
    - name: p3
      weight: 0.14
      start_epoch: 60
      ramp_epochs: 4
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 224
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00032
        beta_fgd: 0.00005
        gamma_fgd: 0.00018
        lambda_fgd: 0.000001
