__include__: [
  '../deimv2/deimv2_hgnetv2_atto_coco.yml'
]

output_dir: ./outputs/distill_deimv2/hgnetv2_atto_from_n_encoder

model: DEIMFGDDistiller

last_epoch: 468
epochs: 500

DEIMFGDDistiller:
  student_ckpt: ./best/deimv2_hgnetv2_atto_coco.pth
  student:
    type: DEIM
    backbone:
      type: HGNetv2
      name: 'Atto'
      return_idx: [2]
      freeze_at: -1
      freeze_norm: false
      use_lab: true
    encoder:
      type: LiteEncoder
      in_channels: [256]
      feat_strides: [16]
      hidden_dim: 64
      expansion: 0.34
      depth_mult: 0.5
      act: silu
    decoder:
      type: DEIMTransformer
      feat_channels: [64, 64]
      feat_strides: [16, 32]
      hidden_dim: 64
      num_levels: 2
      num_points: [4, 2]
      dim_feedforward: 160
      num_layers: 3
      eval_idx: -1
      num_queries: 100
  teacher:
    type: DEIM
    backbone:
      type: HGNetv2
      name: 'B0'
      return_idx: [2, 3]
      freeze_at: -1
      freeze_norm: false
      use_lab: true
    encoder:
      type: HybridEncoder
      in_channels: [512, 1024]
      feat_strides: [16, 32]
      hidden_dim: 128
      use_encoder_idx: [1]
      num_encoder_layers: 1
      nhead: 8
      dim_feedforward: 512
      expansion: 0.34
      depth_mult: 0.5
      act: silu
      version: dfine
      csp_type: csp2
      fuse_op: sum
      eval_spatial_size: [640, 640]
    decoder:
      type: DEIMTransformer
      feat_channels: [128, 128]
      feat_strides: [16, 32]
      hidden_dim: 128
      num_levels: 2
      eval_spatial_size: [640, 640]
      dim_feedforward: 512
      num_layers: 3
      eval_idx: -1
      num_points: [6, 6]
  feature_pairs:
    - name: c4
      student_index: 0
      teacher_index: 0
      meta:
        source: encoder
        start_epoch: 468
  teacher_ckpt: ./best/deimv2_hgnetv2_n_coco.pth

DEIMCriterion:
  distill_cfg:
    - name: c4
      weight: 0.28
      start_epoch: 468
      ramp_epochs: 6
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 64
        teacher_channels: 128
        temp: 0.9
        alpha_fgd: 0.00028
        beta_fgd: 0.00005
        gamma_fgd: 0.00016
        lambda_fgd: 0.000001

train_dataloader:
  collate_fn:
    stop_epoch: 468
