__include__: [../deimv2/deimv2_hgnetv2_m_coco.yml]

output_dir: ./outputs/distill_deimv2/hgnetv2_m_from_x_backbone

model: DEIMFGDDistiller

DEIMFGDDistiller:
  student_ckpt: ./outputs/deimv2_hgnetv2_m_coco/best_stg1.pth
  student:
    type: DEIM
    backbone:
      type: HGNetv2
      name: 'B2'
      return_idx: [1, 2, 3]
      freeze_at: -1
      freeze_norm: false
      use_lab: true
    encoder:
      type: HybridEncoder
      in_channels: [384, 768, 1536]
      feat_strides: [8, 16, 32]
      hidden_dim: 256
      use_encoder_idx: [2]
      num_encoder_layers: 1
      nhead: 8
      dim_feedforward: 1024
      dropout: 0.0
      enc_act: gelu
      expansion: 0.67
      depth_mult: 0.67
      act: silu
      version: deim
      csp_type: csp2
      fuse_op: sum
    decoder:
      type: DEIMTransformer
      feat_channels: [256, 256, 256]
      feat_strides: [8, 16, 32]
      hidden_dim: 256
      num_levels: 3
      num_layers: 4
      eval_idx: -1
      num_queries: 300
      num_denoising: 100
      label_noise_ratio: 0.5
      box_noise_scale: 1.0
      reg_max: 32
      reg_scale: 4
      layer_scale: 1
      num_points: [3, 6, 3]
      cross_attn_method: default
      query_select_method: default
  teacher:
    type: DEIM
    backbone:
      type: HGNetv2
      name: 'B5'
      return_idx: [1, 2, 3]
      freeze_stem_only: true
      freeze_at: 0
      freeze_norm: true
      use_lab: true
    encoder:
      type: HybridEncoder
      in_channels: [512, 1024, 2048]
      feat_strides: [8, 16, 32]
      hidden_dim: 384
      use_encoder_idx: [2]
      num_encoder_layers: 1
      nhead: 8
      dim_feedforward: 2048
      dropout: 0.0
      enc_act: gelu
      expansion: 1.0
      depth_mult: 1.0
      act: silu
      version: deim
      csp_type: csp2
      fuse_op: sum
    decoder:
      type: DEIMTransformer
      feat_channels: [384, 384, 384]
      feat_strides: [8, 16, 32]
      hidden_dim: 384
      num_levels: 3
      num_layers: 6
      eval_idx: -1
      num_queries: 300
      num_denoising: 100
      label_noise_ratio: 0.5
      box_noise_scale: 1.0
      reg_max: 32
      reg_scale: 8
      layer_scale: 1
      num_points: [3, 6, 3]
      cross_attn_method: default
      query_select_method: default
  feature_pairs:
    - name: c3
      student_index: 0
      teacher_index: 0
      meta:
        source: backbone
        start_epoch: 92
    - name: c4
      student_index: 1
      teacher_index: 1
      meta:
        source: backbone
        start_epoch: 90
    - name: c5
      student_index: 2
      teacher_index: 2
      meta:
        source: backbone
        start_epoch: 90
  teacher_ckpt: ./outputs/deimv2_hgnetv2_x_coco/best_stg1.pth

DEIMCriterion:
  distill_cfg:
    - name: c5
      weight: 0.30
      start_epoch: 90
      ramp_epochs: 6
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 256
        teacher_channels: 384
        temp: 0.9
        alpha_fgd: 0.00036
        beta_fgd: 0.00006
        gamma_fgd: 0.00022
        lambda_fgd: 0.000001
    - name: c4
      weight: 0.22
      start_epoch: 90
      ramp_epochs: 6
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 256
        teacher_channels: 384
        temp: 0.9
        alpha_fgd: 0.00036
        beta_fgd: 0.00006
        gamma_fgd: 0.00022
        lambda_fgd: 0.000001
    - name: c3
      weight: 0.16
      start_epoch: 92
      ramp_epochs: 6
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 256
        teacher_channels: 384
        temp: 0.9
        alpha_fgd: 0.00036
        beta_fgd: 0.00006
        gamma_fgd: 0.00022
        lambda_fgd: 0.000001
