__include__: [
  '../deim_dfine/deim_hgnetv2_n_coco.yml'
]

output_dir: ./outputs/distill_deim_dfine/hgnetv2_n_from_s_encoder

model: DEIMFGDDistiller

last_epoch: 160
epoches: 184

DEIMFGDDistiller:
  student_ckpt: ./best/deim_dfine_hgnetv2_n_coco_160e_with_ema.pth
  student:
    type: DEIM
    backbone:
      type: HGNetv2
      name: 'B0'
      return_idx: [2, 3]
      freeze_at: -1
      freeze_norm: false
      use_lab: true
    encoder:
      type: HybridEncoder
      in_channels: [512, 1024]
      feat_strides: [16, 32]
      hidden_dim: 128
      use_encoder_idx: [1]
      num_encoder_layers: 1
      nhead: 8
      dim_feedforward: 512
      dropout: 0.0
      enc_act: gelu
      expansion: 0.34
      depth_mult: 0.5
      act: silu
      version: dfine
    decoder:
      type: DFINETransformer
      feat_channels: [128, 128]
      feat_strides: [16, 32]
      hidden_dim: 128
      dim_feedforward: 512
      num_levels: 2
      num_layers: 3
      eval_idx: -1
      num_points: [6, 6]
  teacher:
    type: DEIM
    backbone:
      type: HGNetv2
      name: 'B0'
      return_idx: [1, 2, 3]
      freeze_at: -1
      freeze_norm: true
      use_lab: true
    encoder:
      type: HybridEncoder
      in_channels: [256, 512, 1024]
      feat_strides: [8, 16, 32]
      hidden_dim: 256
      use_encoder_idx: [2]
      num_encoder_layers: 1
      nhead: 8
      dim_feedforward: 1024
      dropout: 0.0
      enc_act: gelu
      expansion: 0.5
      depth_mult: 0.34
      act: silu
      version: dfine
      csp_type: csp
      fuse_op: cat
      force_proj: true
    decoder:
      type: DFINETransformer
      feat_channels: [256, 256, 256]
      feat_strides: [8, 16, 32]
      hidden_dim: 256
      dim_feedforward: 1024
      num_levels: 3
      num_layers: 3
      eval_idx: -1
      num_points: [3, 6, 3]
  feature_pairs:
    - name: c4
      student_index: 0
      teacher_index: 1
      meta:
        source: encoder
        start_epoch: 160
    - name: c5
      student_index: 1
      teacher_index: 2
      meta:
        source: encoder
        start_epoch: 160
  teacher_ckpt: ./best/deim_dfine_hgnetv2_s_coco_120e_with_ema.pth

DEIMCriterion:
  distill_cfg:
    - name: c5
      weight: 1.25
      start_epoch: 160
      ramp_epochs: 12
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 128
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00042
        beta_fgd: 0.00007
        gamma_fgd: 0.00024
        lambda_fgd: 0.000001
    - name: c4
      weight: 0.5
      start_epoch: 164
      ramp_epochs: 8
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 128
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00042
        beta_fgd: 0.00007
        gamma_fgd: 0.00024
        lambda_fgd: 0.000001

optimizer:
  lr: 0.0008
  betas: [0.9, 0.999]
  weight_decay: 0.0001

lrsheduler: flatcosine
warmup_iter: 500
flat_epoch: 78
no_aug_epoch: 12
lr_gamma: 1.0

train_dataloader:
  total_batch_size: 32 # total batch size equals to 32 (4 * 8)
  num_workers: 8

val_dataloader:
  total_batch_size: 64 # total batch size equals to 32 (4 * 8)
  num_workers: 8
