__include__: [
  '../deim_rtdetrv2/deim_r34vd_120e_coco.yml'
]

output_dir: ./deim_outputs/distill_deim_rtdetr/r34vd_from_r101vd_backbone

model: DEIMFGDDistiller

DEIMFGDDistiller:
  student_ckpt: ./outputs/deim_rtdetrv2_r34vd_120e_coco/best_stg1.pth
  student:
    type: DEIM
    backbone:
      type: PResNet
      depth: 34
      variant: d
      return_idx: [1, 2, 3]
      num_stages: 4
      freeze_at: -1
      freeze_norm: false
      pretrained: true
    encoder:
      type: HybridEncoder
      in_channels: [128, 256, 512]
      feat_strides: [8, 16, 32]
      hidden_dim: 256
      use_encoder_idx: [2]
      num_encoder_layers: 1
      nhead: 8
      dim_feedforward: 1024
      dropout: 0.0
      enc_act: gelu
      expansion: 0.5
      depth_mult: 1.0
      act: silu
      version: rt_detrv2
    decoder:
      type: RTDETRTransformerv2
      feat_channels: [256, 256, 256]
      feat_strides: [8, 16, 32]
      hidden_dim: 256
      num_levels: 3
      num_layers: 4
      eval_idx: -1
      num_queries: 300
      num_denoising: 100
      label_noise_ratio: 0.5
      box_noise_scale: 1.0
      num_points: [4, 4, 4]
      cross_attn_method: default
      query_select_method: default
  teacher:
    type: DEIM
    backbone:
      type: PResNet
      depth: 101
      variant: d
      return_idx: [1, 2, 3]
      num_stages: 4
      freeze_at: 0
      freeze_norm: true
      pretrained: true
    encoder:
      type: HybridEncoder
      in_channels: [512, 1024, 2048]
      feat_strides: [8, 16, 32]
      hidden_dim: 256
      use_encoder_idx: [2]
      num_encoder_layers: 1
      nhead: 8
      dim_feedforward: 1024
      dropout: 0.0
      enc_act: gelu
      expansion: 1.0
      depth_mult: 1.0
      act: silu
      version: rt_detrv2
    decoder:
      type: RTDETRTransformerv2
      feat_channels: [256, 256, 256]
      feat_strides: [8, 16, 32]
      hidden_dim: 256
      num_levels: 3
      num_layers: 6
      eval_idx: -1
      num_queries: 300
      num_denoising: 100
      label_noise_ratio: 0.5
      box_noise_scale: 1.0
      num_points: [4, 4, 4]
      cross_attn_method: default
      query_select_method: default
  feature_pairs:
    - name: c3
      student_index: 0
      teacher_index: 0
      meta:
        source: backbone
        start_epoch: 118
    - name: c4
      student_index: 1
      teacher_index: 1
      meta:
        source: backbone
        start_epoch: 118
    - name: c5
      student_index: 2
      teacher_index: 2
      meta:
        source: backbone
        start_epoch: 118
  teacher_ckpt: ./outputs/deim_rtdetrv2_r101vd_60e_coco/best_stg1.pth

DEIMCriterion:
  distill_cfg:
    - name: c5
      weight: 0.34
      start_epoch: 118
      ramp_epochs: 6
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 256
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00040
        beta_fgd: 0.00007
        gamma_fgd: 0.00024
        lambda_fgd: 0.000001
    - name: c4
      weight: 0.24
      start_epoch: 118
      ramp_epochs: 6
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 256
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00040
        beta_fgd: 0.00007
        gamma_fgd: 0.00024
        lambda_fgd: 0.000001
    - name: c3
      weight: 0.18
      start_epoch: 118
      ramp_epochs: 6
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 256
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00040
        beta_fgd: 0.00007
        gamma_fgd: 0.00024
        lambda_fgd: 0.000001
