__include__: [
  '../deimv2/deimv2_dinov3_s_coco.yml'
]

output_dir: ./outputs/distill_deimv2_different/dinov3_s_from_dinov3_l_encoder

model: DEIMFGDDistiller

last_epoch: 130
epoches: 154

DEIMFGDDistiller:
  student_ckpt: ./best/deimv2_dinov3_s_coco.pth
  student:
    type: DEIM
    backbone:
      type: DINOv3STAs
      name: vit_tiny
      embed_dim: 192
      weights_path: ./ckpts/vitt_distill.pt
      interaction_indexes: [5, 8, 11]
      num_heads: 3
      conv_inplane: 16
    encoder:
      type: HybridEncoder
      in_channels: [192, 192, 192]
      depth_mult: 0.67
      expansion: 0.34
      hidden_dim: 192
      dim_feedforward: 512
      version: dfine
    decoder:
      type: DEIMTransformer
      feat_channels: [192, 192, 192]
      hidden_dim: 192
      dim_feedforward: 512
      num_layers: 4
      eval_idx: -1
      num_points: [6, 6, 6]
      share_bbox_head: true
      use_gateway: false
  teacher:
    type: DEIM
    backbone:
      type: DINOv3STAs
      name: dinov3_vits16
      embed_dim: 224
      weights_path: ./ckpts/dinov3-vits16-pretrain-lvd1689m.pth
      interaction_indexes: [5, 8, 11]
      finetune: true
      conv_inplane: 32
      hidden_dim: 224
    encoder:
      type: HybridEncoder
      in_channels: [224, 224, 224]
      hidden_dim: 224
      dim_feedforward: 896
      expansion: 1.0
      depth_mult: 1.0
    decoder:
      type: DEIMTransformer
      feat_channels: [224, 224, 224]
      hidden_dim: 224
      dim_feedforward: 1792
      num_layers: 4
      eval_idx: -1
      num_points: [6, 6, 6]
      share_bbox_head: true
      use_gateway: false
  feature_pairs:
    - name: p5
      student_index: 2
      teacher_index: 2
      meta:
        source: encoder
        start_epoch: 120
    - name: p4
      student_index: 1
      teacher_index: 1
      meta:
        source: encoder
        start_epoch: 126
    - name: p3
      student_index: 0
      teacher_index: 0
      meta:
        source: encoder
        start_epoch: 128
  teacher_ckpt: ./best/deimv2_dinov3_l_coco.pth

DEIMCriterion:
  distill_cfg:
    - name: c5
      weight: 0.36
      start_epoch: 130
      ramp_epochs: 12
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 192
        teacher_channels: 224
        temp: 0.9
        alpha_fgd: 0.00032
        beta_fgd: 0.00005
        gamma_fgd: 0.00018
        lambda_fgd: 0.000001
    - name: c4
      weight: 0.24
      start_epoch: 136
      ramp_epochs: 8
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 192
        teacher_channels: 224
        temp: 0.9
        alpha_fgd: 0.00032
        beta_fgd: 0.00005
        gamma_fgd: 0.00018
        lambda_fgd: 0.000001
    - name: c3
      weight: 0.12
      start_epoch: 142
      ramp_epochs: 6
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 192
        teacher_channels: 224
        temp: 0.9
        alpha_fgd: 0.00032
        beta_fgd: 0.00005
        gamma_fgd: 0.00018
        lambda_fgd: 0.000001

train_dataloader:
  collate_fn:
    stop_epoch: 130
