__include__: [../deimv2/deimv2_dinov3_s_coco.yml]

output_dir: ./outputs/distill_deimv2/dinov3_s_from_m_encoder

model: DEIMFGDDistiller

last_epoch: 130
epoches: 154

DEIMFGDDistiller:
  student_ckpt: ./best/deimv2_dinov3_s_coco.pth
  student:
    type: DEIM
    backbone:
      type: DINOv3STAs
      name: vit_tiny
      embed_dim: 192
      weights_path: ./ckpts/vitt_distill.pt
      interaction_indexes: [5, 8, 11]
      num_heads: 3
      finetune: true
    encoder:
      type: HybridEncoder
      in_channels: [192, 192, 192]
      feat_strides: [8, 16, 32]
      depth_mult: 0.67
      expansion: 0.34
      hidden_dim: 192
      dim_feedforward: 512
      num_encoder_layers: 3
      use_encoder_idx: [0, 1, 2]
      version: deim
      csp_type: csp2
      fuse_op: sum
    decoder:
      type: DEIMTransformer
      feat_channels: [192, 192, 192]
      feat_strides: [8, 16, 32]
      hidden_dim: 192
      dim_feedforward: 512
      num_layers: 4
      eval_idx: -1
      num_levels: 3
      num_points: [3, 6, 3]
  teacher:
    type: DEIM
    backbone:
      type: DINOv3STAs
      name: vit_tinyplus
      embed_dim: 256
      weights_path: ./ckpts/vittplus_distill.pt
      interaction_indexes: [5, 8, 11]
      num_heads: 4
      finetune: true
    encoder:
      type: HybridEncoder
      in_channels: [256, 256, 256]
      feat_strides: [8, 16, 32]
      depth_mult: 1.0
      expansion: 0.67
      hidden_dim: 256
      dim_feedforward: 512
      num_encoder_layers: 4
      use_encoder_idx: [0, 1, 2]
      version: deim
      csp_type: csp2
      fuse_op: sum
    decoder:
      type: DEIMTransformer
      feat_channels: [256, 256, 256]
      feat_strides: [8, 16, 32]
      hidden_dim: 256
      dim_feedforward: 512
      num_layers: 4
      eval_idx: -1
      num_levels: 3
      num_points: [6, 6, 6]
  feature_pairs:
    - name: c5
      student_index: 2
      teacher_index: 2
      meta:
        source: encoder
        start_epoch: 130
    - name: c4
      student_index: 1
      teacher_index: 1
      meta:
        source: encoder
        start_epoch: 134
    - name: c3
      student_index: 0
      teacher_index: 0
      meta:
        source: encoder
        start_epoch: 138
  teacher_ckpt: ./best/deimv2_dinov3_m_coco.pth

DEIMCriterion:
  distill_cfg:
    - name: c5
      weight: 1.25
      start_epoch: 130
      ramp_epochs: 12
      start_weight: 0.2
      loss:
        type: FGDFeatureLoss
        student_channels: 192
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00034
        beta_fgd: 0.00005
        gamma_fgd: 0.00018
        lambda_fgd: 0.000001
    - name: c4
      weight: 0.36
      start_epoch: 134
      ramp_epochs: 8
      start_weight: 0.1
      loss:
        type: FGDFeatureLoss
        student_channels: 192
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00034
        beta_fgd: 0.00005
        gamma_fgd: 0.00018
        lambda_fgd: 0.000001
    - name: c3
      weight: 0.14
      start_epoch: 138
      ramp_epochs: 4
      start_weight: 0.08
      loss:
        type: FGDFeatureLoss
        student_channels: 192
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00034
        beta_fgd: 0.00005
        gamma_fgd: 0.00018
        lambda_fgd: 0.000001
