__include__: [../deimv2/deimv2_hgnetv2_n_coco.yml]

output_dir: ./outputs/distill_deimv2/hgnetv2_n_from_s_backbone

model: DEIMFGDDistiller

DEIMFGDDistiller:
  student_ckpt: ./best/deimv2_hgnetv2_n_coco.pth
  student:
    type: DEIM
    backbone:
      type: HGNetv2
      name: 'B0'
      return_idx: [2, 3]
      freeze_at: -1
      freeze_norm: false
      use_lab: true
    encoder:
      type: HybridEncoder
      in_channels: [512, 1024]
      feat_strides: [16, 32]
      hidden_dim: 128
      use_encoder_idx: [1]
      num_encoder_layers: 1
      nhead: 8
      dim_feedforward: 512
      dropout: 0.0
      enc_act: gelu
      expansion: 0.34
      depth_mult: 0.5
      act: silu
      version: dfine
    decoder:
      type: DEIMTransformer
      feat_channels: [128, 128]
      feat_strides: [16, 32]
      hidden_dim: 128
      num_levels: 2
      num_layers: 3
      eval_idx: -1
      num_queries: 300
      num_denoising: 100
      label_noise_ratio: 0.5
      box_noise_scale: 1.0
      reg_max: 32
      reg_scale: 4
      layer_scale: 1
      num_points: [6, 6]
  teacher:
    type: DEIM
    backbone:
      type: HGNetv2
      name: 'B0'
      return_idx: [1, 2, 3]
      freeze_at: -1
      freeze_norm: false
      use_lab: true
    encoder:
      type: HybridEncoder
      in_channels: [256, 512, 1024]
      feat_strides: [8, 16, 32]
      hidden_dim: 256
      use_encoder_idx: [2]
      num_encoder_layers: 1
      nhead: 8
      dim_feedforward: 1024
      dropout: 0.0
      enc_act: gelu
      expansion: 0.5
      depth_mult: 0.34
      act: silu
      version: dfine
    decoder:
      type: DEIMTransformer
      feat_channels: [256, 256, 256]
      feat_strides: [8, 16, 32]
      hidden_dim: 256
      num_levels: 3
      num_layers: 3
      eval_idx: -1
      num_queries: 300
      num_denoising: 100
      label_noise_ratio: 0.5
      box_noise_scale: 1.0
      reg_max: 32
      reg_scale: 4
      layer_scale: 1
      num_points: [3, 6, 3]
  feature_pairs:
    - name: c4
      student_index: 0
      teacher_index: 1
      meta:
        source: backbone
        start_epoch: 150
    - name: c5
      student_index: 1
      teacher_index: 2
      meta:
        source: backbone
        start_epoch: 148
  teacher_ckpt: ./outputs/deimv2_hgnetv2_s_coco/best_stg1.pth

DEIMCriterion:
  distill_cfg:
    - name: c5
      weight: 0.32
      start_epoch: 148
      ramp_epochs: 6
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 128
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00042
        beta_fgd: 0.00007
        gamma_fgd: 0.00024
        lambda_fgd: 0.000001
    - name: c4
      weight: 0.22
      start_epoch: 150
      ramp_epochs: 6
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 128
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00042
        beta_fgd: 0.00007
        gamma_fgd: 0.00024
        lambda_fgd: 0.000001
