__include__: [
  '../deimv2/deimv2_hgnetv2_atto_coco.yml'
]
print_freq: 250
output_dir: ./outputs/distill_deimv2_different/hgnetv2_atto_from_dinov3_s_backbone

model: DEIMFGDDistiller

last_epoch: 500
epoches: 524

DEIMFGDDistiller:
  student_ckpt: ./best/deimv2_hgnetv2_atto_coco.pth
  student:
    type: DEIM
    backbone:
      type: HGNetv2
      name: 'Atto'
      return_idx: [2]
      freeze_at: -1
      freeze_norm: false
      use_lab: true
    encoder:
      type: LiteEncoder
      in_channels: [256]
      feat_strides: [16]
      hidden_dim: 64
      expansion: 0.34
      depth_mult: 0.5
      act: silu
    decoder:
      type: DEIMTransformer
      feat_channels: [64, 64]
      feat_strides: [16, 32]
      hidden_dim: 64
      num_levels: 2
      num_points: [4, 2]
      dim_feedforward: 160
      num_layers: 3
      eval_idx: -1
      num_queries: 100
      share_bbox_head: True
      use_gateway: False
  teacher:
    type: DEIM
    backbone:
      type: DINOv3STAs
      name: vit_tiny
      embed_dim: 192
      weights_path: ./ckpts/vitt_distill.pt
      interaction_indexes: [5, 8, 11]
      num_heads: 3
      finetune: true
    encoder:
      type: HybridEncoder
      in_channels: [192, 192, 192]
      depth_mult: 0.67
      expansion: 0.34
      hidden_dim: 192
      dim_feedforward: 512
      use_encoder_idx: [2]
      version: deim
      csp_type: csp2
      fuse_op: sum
    decoder:
      type: DEIMTransformer
      feat_channels: [192, 192, 192]
      hidden_dim: 192
      dim_feedforward: 512
      num_layers: 4
      eval_idx: -1
      num_levels: 3
      num_points: [3, 6, 3]
  feature_pairs:
    - name: c4
      student_index: 0
      teacher_index: 1
      meta:
        source: backbone
        start_epoch: 468
  teacher_ckpt: ./best/deimv2_dinov3_s_coco.pth

DEIMCriterion:
  distill_cfg:
    - name: c4
      weight: 1.25
      start_epoch: 500
      ramp_epochs: 2
      start_weight: 0.35
      loss:
        type: FGDFeatureLoss
        student_channels: 256
        teacher_channels: 192
        temp: 0.9
        alpha_fgd: 0.00028
        beta_fgd: 0.00005
        gamma_fgd: 0.00016
        lambda_fgd: 0.000001

train_dataloader:
  total_batch_size: 96
  collate_fn:
    stop_epoch: 468
