__include__: [
  '../deim_dfine/deim_hgnetv2_n_coco.yml'
]

output_dir: ./outputs/distill_deim_dfine/hgnetv2_n_from_x_encoder

model: DEIMFGDDistiller

last_epoch: 160
epoches: 184

DEIMFGDDistiller:
  student_ckpt: ./best/deim_dfine_hgnetv2_n_coco_160e.pth
  student:
    type: DEIM
    backbone:
      type: HGNetv2
      name: 'B0'
      return_idx: [2, 3]
      freeze_at: -1
      freeze_norm: false
      use_lab: true
    encoder:
      type: HybridEncoder
      in_channels: [512, 1024]
      feat_strides: [16, 32]
      hidden_dim: 128
      use_encoder_idx: [1]
      num_encoder_layers: 1
      nhead: 8
      dim_feedforward: 512
      dropout: 0.0
      enc_act: gelu
      expansion: 0.34
      depth_mult: 0.5
      act: silu
      version: dfine
    decoder:
      type: DFINETransformer
      feat_channels: [128, 128]
      feat_strides: [16, 32]
      hidden_dim: 128
      dim_feedforward: 512
      num_levels: 2
      num_layers: 3
      eval_idx: -1
      num_points: [6, 6]
  teacher:
    type: DEIM
    backbone:
      type: HGNetv2
      name: 'B5'
      return_idx: [1, 2, 3]
      freeze_stem_only: true
      freeze_at: 0
      freeze_norm: true
      use_lab: false
    encoder:
      type: HybridEncoder
      in_channels: [512, 1024, 2048]
      feat_strides: [8, 16, 32]
      hidden_dim: 384
      use_encoder_idx: [2]
      num_encoder_layers: 1
      nhead: 8
      dim_feedforward: 2048
      dropout: 0.0
      enc_act: gelu
      expansion: 1.0
      depth_mult: 1.0
      act: silu
      version: dfine
    decoder:
      type: DFINETransformer
      feat_channels: [384, 384, 384]
      feat_strides: [8, 16, 32]
      hidden_dim: 256
      num_levels: 3
      num_layers: 6
      eval_idx: -1
      num_queries: 300
      num_denoising: 100
      label_noise_ratio: 0.5
      box_noise_scale: 1.0
      reg_max: 32
      reg_scale: 8
      layer_scale: 1
      num_points: [3, 6, 3]
      cross_attn_method: default
      query_select_method: default
  feature_pairs:
    - name: c4
      student_index: 0
      teacher_index: 1
      meta:
        source: encoder
        start_epoch: 162
    - name: c5
      student_index: 1
      teacher_index: 2
      meta:
        source: encoder
        start_epoch: 160
  teacher_ckpt: ./best/deim_dfine_hgnetv2_x_coco_50e.pth

DEIMCriterion:
  distill_cfg:
    - name: c5
      weight: 1.25
      start_epoch: 160
      ramp_epochs: 0
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 128
        teacher_channels: 384
        temp: 0.9
        alpha_fgd: 0.00038
        beta_fgd: 0.00006
        gamma_fgd: 0.00022
        lambda_fgd: 0.000001
    - name: c4
      weight: 0.48
      start_epoch: 164
      ramp_epochs: 0
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 128
        teacher_channels: 384
        temp: 0.9
        alpha_fgd: 0.00038
        beta_fgd: 0.00006
        gamma_fgd: 0.00022
        lambda_fgd: 0.000001

train_dataloader:
  total_batch_size: 24 # total batch size equals to 32 (4 * 8)
  num_workers: 8
  collate_fn:
    stop_epoch: 148

val_dataloader:
  total_batch_size: 64 # total batch size equals to 32 (4 * 8)
  num_workers: 8
