__include__: [
  '../deim_rtdetrv2/deim_r18vd_120e_coco.yml'
]

output_dir: ./outputs/distill/deimv2_r18vd_from_r50vd_encoder

model: DEIMFGDDistiller

DEIMFGDDistiller:
  student:
    type: DEIM
    backbone:
      type: PResNet
      depth: 18
      variant: d
      return_idx: [2, 3]
      num_stages: 4
      freeze_at: -1
      freeze_norm: false
      pretrained: true
    encoder:
      type: HybridEncoder
      in_channels: [256, 512]
      feat_strides: [16, 32]
      hidden_dim: 128
      use_encoder_idx: [1]
      num_encoder_layers: 1
      nhead: 8
      dim_feedforward: 512
      dropout: 0.0
      enc_act: gelu
      expansion: 0.34
      depth_mult: 0.5
      act: silu
    decoder:
      type: DFINETransformer
      feat_channels: [128, 128]
      feat_strides: [16, 32]
      hidden_dim: 128
      dim_feedforward: 512
      num_levels: 2
      num_layers: 3
      eval_idx: -1
      num_queries: 300
      num_denoising: 100
      label_noise_ratio: 0.5
      box_noise_scale: 1.0
      reg_max: 32
      reg_scale: 4
      layer_scale: 1
      num_points: [6, 6]
      cross_attn_method: default
      query_select_method: default
  teacher:
    type: DEIM
    backbone:
      type: PResNet
      depth: 50
      variant: d
      return_idx: [1, 2, 3]
      num_stages: 4
      freeze_at: 0
      freeze_norm: true
      pretrained: true
    encoder:
      type: HybridEncoder
      in_channels: [512, 1024, 2048]
      feat_strides: [8, 16, 32]
      hidden_dim: 256
      use_encoder_idx: [2]
      num_encoder_layers: 1
      nhead: 8
      dim_feedforward: 1024
      dropout: 0.0
      enc_act: gelu
      expansion: 1.0
      depth_mult: 1.0
      act: silu
      version: rt_detrv2
    decoder:
      type: RTDETRTransformerv2
      feat_channels: [256, 256, 256]
      feat_strides: [8, 16, 32]
      hidden_dim: 256
      num_levels: 3
      num_layers: 6
      num_queries: 300
      num_denoising: 100
      label_noise_ratio: 0.5
      box_noise_scale: 1.0
      eval_idx: -1
      num_points: [4, 4, 4]
      query_pos_method: as_reg
  feature_pairs:
    - name: c4
      student_index: 0
      teacher_index: 1
      meta:
        source: encoder
        start_epoch: 112
    - name: c5
      student_index: 1
      teacher_index: 2
      meta:
        source: encoder
        start_epoch: 96
  teacher_ckpt: ../DEIM/teacher_outputs/deim_rtdetrv2_r50vd_60e_coco/best_stg1.pth

DEIMCriterion:
  distill_cfg:
    - name: c5
      weight: 0.20
      start_epoch: 96
      ramp_epochs: 12
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 128
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00045
        beta_fgd: 0.00006
        gamma_fgd: 0.00025
        lambda_fgd: 0.000001
    - name: c4
      weight: 0.14
      start_epoch: 112
      ramp_epochs: 12
      start_weight: 0.0
      loss:
        type: FGDFeatureLoss
        student_channels: 128
        teacher_channels: 256
        temp: 0.9
        alpha_fgd: 0.00045
        beta_fgd: 0.00006
        gamma_fgd: 0.00025
        lambda_fgd: 0.000001

flat_epoch: 7800
no_aug_epoch: 12

train_dataloader:
  total_batch_size: 48
  num_workers: 12
  collate_fn:
    mixup_epochs: [4, 78]
    stop_epoch: 148

val_dataloader:
  total_batch_size: 64
  num_workers: 8
